version: "3"

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

